# Проект 4. Авиарейсы без потерь

In [2]:
# Импорт библиотек

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

### Первичный осмотр данных

In [7]:
df = pd.read_csv('data.csv')

In [8]:
df.head()

flight_id departure_city destination                model  distance  \
0   136464.0          Anapa      Moscow       Boeing 737-300      1200   
1   136250.0          Anapa      Moscow       Boeing 737-300      1200   
2   136807.0          Anapa    Belgorod  Sukhoi Superjet-100       620   
3   136642.0          Anapa    Belgorod  Sukhoi Superjet-100       620   
4   136122.0          Anapa      Moscow       Boeing 737-300      1200   

   tickets_sold  max_seats  load_factor  fuel_cons_total    revenue  \
0           100        130     0.769231           4188.0  1398000.0   
1            99        130     0.761538           4188.0  1407800.0   
2            68         97     0.701031           1742.2   531000.0   
3            64         97     0.659794           1742.2   531000.0   
4            97        130     0.746154           4188.0  1431000.0   

   fuel_costs   other_costs   total_costs         profit  
0    192648.0  1.324265e+06  1.516913e+06 -118913.385827  
1    192648.0  1.324265e+06  1.516913e+06 -109113.385827  
2     80141.2  5.508919e+05  6.310331e+05 -100033.070866  
3     80141.2  5.508919e+05  6.310331e+05 -100033.070866  
4    192648.0  1.324265e+06  1.516913e+06  -85913.385827

In [9]:
df.shape

(127, 14)

In [11]:
df = df.dropna()

In [12]:
df.shape

(118, 14)

In [13]:
df.describe()

flight_id     distance  tickets_sold   max_seats  load_factor  \
count     118.000000   118.000000    118.000000  118.000000   118.000000   
mean   136533.440678   910.000000    101.652542  113.500000     0.899950   
std       261.971994   291.236679     14.295643   16.570363     0.081705   
min    136119.000000   620.000000     64.000000   97.000000     0.659794   
25%    136286.250000   620.000000     95.000000   97.000000     0.835052   
50%    136528.500000   910.000000     97.000000  113.500000     0.898454   
75%    136768.500000  1200.000000    111.750000  130.000000     0.989691   
max    136956.000000  1200.000000    130.000000  130.000000     1.000000   

       fuel_cons_total       revenue     fuel_costs   other_costs  \
count       118.000000  1.180000e+02     118.000000  1.180000e+02   
mean       2965.100000  1.176506e+06  136394.600000  9.375786e+05   
std        1228.114949  4.794251e+05   56493.287655  3.883357e+05   
min        1742.200000  5.310000e+05   80141.200000  5.508919e+05   
25%        1742.200000  7.464000e+05   80141.200000  5.508919e+05   
50%        2965.100000  1.081650e+06  136394.600000  9.375786e+05   
75%        4188.000000  1.625850e+06  192648.000000  1.324265e+06   
max        4188.000000  1.886000e+06  192648.000000  1.324265e+06   

        total_costs         profit  
count  1.180000e+02     118.000000  
mean   1.073973e+06  102532.703857  
std    4.448290e+05  106347.800921  
min    6.310331e+05 -118913.385827  
25%    6.310331e+05   28981.692913  
50%    1.073973e+06  115366.929134  
75%    1.516913e+06  134266.929134  
max    1.516913e+06  369086.614173

### Анализ убыточности рейсов

In [77]:
print(f'Доля убыточных рейсов составляет {round(df[df.profit < 0].shape[0] / df.shape[0] * 100, 2)} процентов')

Доля убыточных рейсов составляет 15.25 процентов


In [27]:
# ID всех убыточных рейсов

unprofitable_flights = np.array(df[df.profit < 0].flight_id)

In [28]:
unprofitable_flights

array([136464., 136250., 136807., 136642., 136122., 136178., 136360.,
       136204., 136844., 136887., 136383., 136922., 136202., 136620.,
       136486., 136823., 136888., 136937.])

In [29]:
# Статистика убыточных рейсов по городам прилета

df[df.profit < 0].groupby('destination')['flight_id'].count()

destination
Belgorod    9
Moscow      9
Name: flight_id, dtype: int64

In [43]:
good_flights = df[df.profit >= 0].sort_values(by='profit', ascending=False)

In [32]:
bad_flights = df[df.profit < 0].sort_values('destination')

In [34]:
bad_flights.head()

flight_id departure_city destination                model  distance  \
8    136844.0          Anapa    Belgorod  Sukhoi Superjet-100       620   
15   136823.0          Anapa    Belgorod  Sukhoi Superjet-100       620   
13   136620.0          Anapa    Belgorod  Sukhoi Superjet-100       620   
11   136922.0          Anapa    Belgorod  Sukhoi Superjet-100       620   
9    136887.0          Anapa    Belgorod  Sukhoi Superjet-100       620   

    tickets_sold  max_seats  load_factor  fuel_cons_total   revenue  \
8             79         97     0.814433           1742.2  575100.0   
15            78         97     0.804124           1742.2  620400.0   
13            79         97     0.814433           1742.2  613500.0   
11            76         97     0.783505           1742.2  607800.0   
9             78         97     0.804124           1742.2  595200.0   

    fuel_costs    other_costs    total_costs        profit  
8      80141.2  550891.870866  631033.070866 -55933.070866  
15     80141.2  550891.870866  631033.070866 -10633.070866  
13     80141.2  550891.870866  631033.070866 -17533.070866  
11     80141.2  550891.870866  631033.070866 -23233.070866  
9      80141.2  550891.870866  631033.070866 -35833.070866

In [36]:
# ID всех убыточных рейсов в Москву

bad_flights_Moscow = np.array(bad_flights[bad_flights.destination == 'Moscow'].flight_id)

In [37]:
print(bad_flights_Moscow)

array([136204., 136178., 136122., 136383., 136202., 136486., 136250.,
       136360., 136464.])

In [38]:
# ID всех убыточных рейсов в Белгород

bad_flights_Belgorod = np.array(bad_flights[bad_flights.destination == 'Belgorod'].flight_id)

In [39]:
bad_flights_Belgorod

array([136844., 136823., 136620., 136922., 136887., 136888., 136937.,
       136642., 136807.])

In [79]:
good_flights.head()

flight_id departure_city destination           model  distance  \
117   136226.0          Anapa      Moscow  Boeing 737-300      1200   
116   136316.0          Anapa      Moscow  Boeing 737-300      1200   
115   136403.0          Anapa      Moscow  Boeing 737-300      1200   
114   136389.0          Anapa      Moscow  Boeing 737-300      1200   
113   136423.0          Anapa      Moscow  Boeing 737-300      1200   

     tickets_sold  max_seats  load_factor  fuel_cons_total    revenue  \
117           130        130     1.000000           4188.0  1886000.0   
116           130        130     1.000000           4188.0  1886000.0   
115           129        130     0.992308           4188.0  1873800.0   
114           129        130     0.992308           4188.0  1873800.0   
113           129        130     0.992308           4188.0  1849400.0   

     fuel_costs   other_costs   total_costs         profit  
117    192648.0  1.324265e+06  1.516913e+06  369086.614173  
116    192648.0  1.324265e+06  1.516913e+06  369086.614173  
115    192648.0  1.324265e+06  1.516913e+06  356886.614173  
114    192648.0  1.324265e+06  1.516913e+06  356886.614173  
113    192648.0  1.324265e+06  1.516913e+06  332486.614173

In [45]:
# Средняя прибыльность прибыльных рейсов по городам прилета

good_flights.groupby('destination')['profit'].mean()

destination
Belgorod    100756.929134
Moscow      159750.614173
Name: profit, dtype: float64

Рейсы в Москву в зимние месяцы в среднем прибыльнее, чем рейсы в Белгород

In [52]:
# Средняя прибыльность прибыльных рейсов по моделям самолета

good_flights.groupby('model')['profit'].mean()

model
Boeing 737-300         159750.614173
Sukhoi Superjet-100    100756.929134
Name: profit, dtype: float64

Боинг в среднем существеннее прибыльнее Сухого

In [51]:
print(f'Средняя прибыльность всех зимних рейсов из Анапы составляет {round(df.describe().iloc[1, -1], 2)} руб')

Средняя прибыльность всех зимних рейсов из Анапы составляет 102532.7 руб


Проверим гипотезу о наличии положительной корреляции между заполняемостью и прибыльностью рейсов

In [46]:
corr_mat = df.loc[:, ['load_factor', 'profit']].corr()

In [47]:
corr_mat

load_factor    profit
load_factor     1.000000  0.733636
profit          0.733636  1.000000

Наблюдаем сильную положительную корреляцию. Чем выше доля заполненных мест в самолете, тем выше прибыльность рейса.